CREATE DATABASE IF NOT EXISTS fandango;
use fandango;

DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
  id INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(50) NOT NULL,
  Title VARCHAR(50),
  Mooz INT NOT NULL,
  Review VARCHAR(500),
  Helpful INT DEFAULT 0,
  PRIMARY KEY (id)
);

LOAD DATA LOCAL INFILE './database/data.csv'
INTO TABLE movies
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;